---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api-sa
  namespace: formation-lap
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::570795932693:role/formation-lap-backend-api-s3-irsa
