apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: formation-lap
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_CLIENT_SECRET: ""
