apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-users
  template:
    metadata:
      labels:
        app: ott-users
    spec:
      containers:
        - name: ott-users
          image: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/y2om-user-service
          ports:
            - containerPort: 8000
          env:
            - name: RDS_PROXY_SEOUL
              value: formation-lap-kor-rds-proxy.proxy-c902seqsaaps.ap-northeast-2.rds.amazonaws.com
            - name: DB_USER
              value: proxy_admin
            - name: DB_PASS
              value: test1234
            - name: DB_NAME
              value: ott_db
            - name: REGION_NAME
              value: ap-northeast-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-content
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-content
  template:
    metadata:
      labels:
        app: ott-content
    spec:
      containers:
        - name: ott-content
          image: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/ott-content
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: formation-lap-kor-rds-proxy.proxy-c902seqsaaps.ap-northeast-2.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: StrongPassword123!
            - name: DB_NAME
              value: ott_db
            - name: REGION_NAME
              value: ap-northeast-2

