apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: formation-lap
spec:
  selector:
    app: backend-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
