apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: formation-lap
spec:
  selector:
    app: video-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
