---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: formation-lap
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: ""
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  MEILISEARCH_API_KEY: "masterKey1234567890"
  DATABASE_URL: "mysql+pymysql://admin:StrongPassword123!@kor-aurora-mysql.cluster-c902seqsaaps.ap-northeast-2.rds.amazonaws.com:3306/ott_db?charset=utf8mb4"
