---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api-sa
  namespace: formation-lap
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::087730891580:role/y2om-backend-api-s3-irsa
